---
- hosts: localhost
  pre_tasks:
    - include_vars: ../defaults/main.yml
    - include_vars: ../vars/main.yml
    - name: add jenkins to inventory
      add_host:
        name: "{{ jenkins_host }}"

- hosts: "{{ jenkins_host }}"
  remote_user: "{{ remote_user }}"
  become: yes  
  tasks:
    - name: lookup-pw
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: pw
    - debug:
        msg: "-->http://{{ jenkins_host }}:8080 user:admin; pw: {{ pw.stdout }} "
