- name: Get VPC-Router
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/routers"
    method: GET
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    #body: "{{ lookup('template', '../templates/request.json.j2')|to_json }}"
  register: vpc_router

- name: fact_router
  set_fact: router_fact="{{ vpc_router['json']|json_query(query_router) }}"
- name: fact_routes
  set_fact: routes_fact="{{ vpc_router['json']|json_query(query_routes) }}"
- debug: msg="{{ routes_fact }}"