---
mesos_install_mode: "master" # {master|slave|master-slave}
zookeeper_hostnames: "{{ mesos_hostname }}:2181"

mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_options: "--log_dir=$LOGS"
mesos_work_dir: "/var/lib/mesos"
mesos_zookeeper_masters: "zk://{{ zookeeper_hostnames }}/mesos" 

mesos_ip: "{{ ansible_eth0.ipv4.address }}"
mesos_quorum: "{{ ((groups['mesos-masters'] | length) / 2) | round | int }}"
mesos_containerizers: "docker,mesos"
mesos_executor_timeout: "5mins"
mesos_port: "5050"
