- name: create image from template ecs!
  uri:
    url: "{{ AUTH_URL_IMS }}/v2/cloudimages/action"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', '../templates/request.json.j2')|to_json }}"