- name: Request ecs list from AUTH API
  uri:
    url: "{{ AUTH_URL_ECS }}/servers/detail?name={{ cluster_id }}-master"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: ecslist

#- debug:
#    msg: "{{ ecslist.json }}"
