---
query_zoo: "security_groups[?name=='{{ cluster_id }}-zookeeper'].id"
query_master: "security_groups[?name=='{{ cluster_id }}-master'].id"
query_agent: "security_groups[?name=='{{ cluster_id }}-agent'].id"
query_public: "security_groups[?name=='{{ cluster_id }}-public'].id"