- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/security-group-rules"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204,409
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', '../templates/request.json.j2')|to_json }}"
  register: secgrouprule
  when: secgrouprule_direction is defined
